[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/api"
  to = "/api/index.json"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }


[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/*"
to = "/404.html"
  status = 404
  force = true
